#!/bin/sh
DAEMON=/usr/bin/resetnet
NAME=resetnet
DESC="ampgw resetnet"
ARGS=""

set -e

case "$1" in
    start)
        echo -n "starting $DESC: $NAME... "
	start-stop-daemon -S -x $DAEMON -- $ARGS
	echo "done."
	;;
    stop)
        echo -n "stopping $DESC: $NAME... "
	start-stop-daemon -K -x $DAEMON
	echo "done."
	;;
    status)
	echo -n "${NAME} "
	start-stop-daemon -q -K -t -x $DAEMON
	RET=$?
	if [ "$RET" = "0" ]; then
		PID=`cat /var/run/ampgw.pid`
		echo "($PID) is running"
	else
		echo "is not running"
		exit $RET
	fi
	;;
    restart)
        echo "restarting $DESC: $NAME... "
 	$0 stop
	$0 start
	echo "done."
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac

exit 0
